version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find ./build -type f | xargs shellcheck -e SC2086 -e SC1090 --external-sources
            find ./rootfs/sbin/ -type f | xargs shellcheck -e SC2086 -e SC1090 -e SC2044 --external-sources
            shellcheck -e SC2086 -e SC1090 --external-sources rootfs/etc/docker-gitlab/configure
            shellcheck -e SC2086 -e SC1090 --external-sources rootfs/etc/docker-gitlab/env-defaults
    
  build:
    docker:
      - image: circleci/golang:1-stretch-browsers-legacy
        environment:
          IMAGE_NAME: "datacore/gitlab"

    environment:
      CACHE_VERSION: v4
    steps:
      - checkout

      - setup_remote_docker:
          version: 18.03.1-ce
          docker_layer_caching: true

      - run:
          name: Docker info
          command: |
            docker version
            docker info

      - restore_cache:
          keys:
            - cache-${CACHE_VERSION}-{{ .Branch }}
          paths:
            - /tmp/cache/layers.tar

      - run:
          name: Loading docker cache
          command: |
            if [[ -f /tmp/cache/layers.tar ]]; then
              echo "Loading cache ..."
              docker load -i /tmp/cache/layers.tar
              docker image ls
            else
              echo "Couldn't find any caches"
            fi

      - run:
          name: Build docker image
          no_output_timeout: 1h
          command: |
            make all

      - run:
          name: Launching container for testing
          command: |
            DOCKER_IMAGE=${IMAGE_NAME}:${CIRCLE_TAG:-latest} docker-compose -f ./docker/quickstart.yml up -d
            sleep 60

      - run:
          name: Testing image
          command: |
            docker run --network container:$(DOCKER_IMAGE=${IMAGE_NAME}:${CIRCLE_TAG:-latest} docker-compose -f ./docker/quickstart.yml ps -q gitlab-test) \
              appropriate/curl --retry 240 --retry-delay 10 --retry-connrefused http://localhost/explore

      - run:
          name: Teardown
          command: |
            DOCKER_IMAGE=${IMAGE_NAME}:${CIRCLE_TAG:-latest} docker-compose -f ./docker/quickstart.yml down

      - run:
          name: Generate docker build image cache
          command: |
            mkdir -p /tmp/cache/
            docker save -o /tmp/cache/layers.tar ${IMAGE_NAME}
            
      - save_cache:
          key: cache-${CACHE_VERSION}-{{ .Branch }}
          paths:
            - /tmp/cache/layers.tar

      - run:
          name: Deploy to DockerHub
          command: |
            CIRCLE_TAG=${CIRCLE_TAG:-latest}
            if [ "${CIRCLE_BRANCH}" = "master" ] || [ "${CIRCLE_TAG}" != "latest" ]; then
              if [ -n "${DOCKERHUB_USERNAME}" ] && [ -n "${DOCKERHUB_PASSWORD}" ]; then
                echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
                docker push ${IMAGE_NAME}:${CIRCLE_TAG:-latest}
              fi
            fi

workflows:
  version: 2
  build-and-test:
    jobs:
      - shellcheck:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
