version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find ./build -type f | xargs shellcheck -e SC2086 -e SC1090 --external-sources
            find ./rootfs/usr/ -type f | xargs shellcheck -e SC2086 -e SC1090 --external-sources
            find ./rootfs/sbin/ -type f | xargs shellcheck -e SC2086 -e SC1090 --external-sources
            shellcheck -e SC2086 -e SC1090 --external-sources rootfs/etc/docker-gitlab/configure
            shellcheck -e SC2086 -e SC1090 --external-sources rootfs/etc/docker-gitlab/env-defaults
    
  build:
    docker:
      - image: circleci/golang:1-stretch-browsers-legacy
        environment:
          IMAGE_NAME: "gjrtimmer/gitlab"

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.03.1-ce

      - run:
          name: Docker info
          command: |
            docker version
            docker info

      - restore_cache:
          keys:
            - cache-v2-{{ .Branch }}
          paths:
            - /tmp/cache/layers.tar

      - run:
          name: Loading docker cache
          command: |
            if [[ -f /tmp/cache/layers.tar ]]; then
              echo "Loading cache ..."
              docker load -i /tmp/cache/layers.tar
              docker image ls
            else
              echo "Couldn't find any caches"
            fi

      - run:
          name: Build docker image
          command: |
            make all

      - run:
          name: Launching container for testing
          command: |
            DOCKER_IMAGE=${IMAGE_NAME} docker-compose -f ./docker/quickstart.yml up -d
            sleep 120

      - run:
          name: Testing image
          command: |
            docker run --network container:$(docker-compose -f ./docker/quickstart.yml ps -q gitlab-test) \
              appropriate/curl --retry 120 --retry-delay 15 --retry-connrefused http://localhost/explore

      - run:
          name: Teardown
          command: |
            DOCKER_IMAGE=${IMAGE_NAME} docker-compose -f ./docker/quickstart.yml down

      - run:
          name: Generate docker build image cache
          command: |
            mkdir -p /tmp/cache/
            docker save -o /tmp/cache/layers.tar ${IMAGE_NAME}

      - save_cache:
          key: cache-v2-{{ .Branch }}
          paths:
            - /tmp/cache/layers.tar

workflows:
  version: 2
  build-and-test:
    jobs:
      - shellcheck
      - build
